"""empty message

Revision ID: 057e12681951
Revises: 093576223149
Create Date: 2026-09-03 03:45:51.251467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057e12681951'
down_revision = '093576223149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imgs_event', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('imgs_event')
        batch_op.drop_column('capacity')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
